
services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Blog
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - data:/var/lib/mysql
            - ./init-db:/docker-entrypoint-initdb.d 
        ports:
            - 3316:3306
        healthcheck:
            test: ["CMD-SHELL", "mariadb -u admin --password=admin -D Blog -e 'SHOW TABLES;' || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10

    web:
        build: .
        command: >
            sh -c "python manage.py migrate &&
            python manage.py loaddata /app/data.json &&
            python manage.py runserver 0.0.0.0:8000"
        restart: always
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            db:
                condition: service_healthy

volumes:
    data:
