# Generated by Django 5.1.6 on 2025-03-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
