# Generated by Django 5.1.6 on 2025-03-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
